steps:
# install dependencies
- id: install-dependencies
  name: node:14
  entrypoint: npm
  args: ['install']

# lint and test
- name: node:14
  entrypoint: npm
  args: ['run', 'lint']
- name: node:14
  entrypoint: npm
  args: ['test']

# run cypress
- name: cypress/included:8.5.0
  entrypoint: 'npm'
  args: ['run', 'ci']

options:
  machineType: 'E2_HIGHCPU_8'
