steps:
# install dependencies
- name: 'node:14'
  id: install-dependencies
  entrypoint: 'npm'
  args: ['install']

# lint and test
- name: 'node:14'
  id: Run lint
  entrypoint: 'npm'
  args: ['run', 'lint']
- name: 'node:14'
  id: Run test
  entrypoint: 'npm'
  args: ['test']

# run cypress
- name: cypress/included:8.6.0
  id: Run E2Es
  entrypoint: 'npm'
  args: ['run', 'ci']

options:
  machineType: 'E2_HIGHCPU_8'
